'use strict';

const assert = require('assert');
const fs = require('fs');

const pkg = JSON.parse(fs.readFileSync('docs/demo-custom-ui-world.tavern-world.json', 'utf8'));
const appSource = fs.readFileSync('public/app.js', 'utf8');
const world = pkg.content.world;
const extension = world.ui.extension;
assert.strictEqual(pkg.spec, 'tavern_world_package');
assert.strictEqual(world.id, 'world-custom-ui-lab');
assert.strictEqual(world.ui.layout, 'custom');
assert.deepStrictEqual(world.ui.shell, { navigation: 'hide', topbar: 'hide', fullscreen: true, escape: 'fullscreen' });
assert.strictEqual(extension.immersive, false);
assert.deepStrictEqual(Object.values(world.ui.regions).map(item => item.mode), Array(8).fill('hide'));
assert.doesNotMatch(extension.html, /data-tavern-narrative/);
assert.doesNotMatch(extension.html, /custom-log|custom-narrative/);
assert.strictEqual((extension.html.match(/data-tavern-messages/g) || []).length, 1);
assert.match(extension.html, /custom-message-stream/);
assert.match(extension.html, /data-tavern-options/);
assert.match(extension.html, /data-tavern-input/);
assert.match(extension.html, /data-custom-action="fullscreen"/);
assert.match(extension.html, /data-custom-action="exit"/);
assert.match(extension.html, /data-custom-action="world-exit"/);
assert.match(extension.html, /data-custom-action="terminal"/);
assert.doesNotMatch(extension.html, /data-tavern-narrative/);
assert.match(extension.js, /TavernExtension\.mvu/);
assert.match(extension.js, /TavernExtension\.action/);
assert.match(extension.js, /TavernExtension\.fullscreen/);
assert.match(extension.js, /TavernExtension\.exitFullscreen/);
assert.match(extension.js, /TavernExtension\.exitWorld/);
assert.match(extension.js, /TavernExtension\.openTerminal/);
assert.match(extension.js, /TavernExtension\.on\('turn\.error'/);
assert.match(appSource, /type: 'immersive\.exit', reason: 'escape'/);
assert.match(appSource, /data\.reason === 'escape' && escapeMode === 'none'/);
assert.doesNotMatch(extension.js, /\}\)\(\)\(\(\)=>/);
assert.match(extension.css, /custom-message-stream/);
assert.match(extension.css, /max-height:none/);
assert.strictEqual(world.runtime.actions[0].effects[0].variableId, 'signal');
console.log('check_custom_ui_world: ok');
